services:
  create-project-api:
    build: ./create-project
    container_name: create-project-api
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:root@localhost:5432/microservices?schema=public
    networks:
      - microservices_network

  reverse-proxy:
    build: ./nginx-proxy
    container_name: api-proxy
    restart: always
    networks:
      - microservices_network
    ports:
      - "80:80"

networks:
  microservices_network:
    driver: bridge