services:
  create-project-api:
    build: ./create-project
    # image: veludeveloper/create-project-api
    container_name: create-project-api
    env_file: ./microservices.env
    environment:
      - PORT=3000
    networks:
      - microservices_network

  signup-api:
    build: ./signup
    # image: veludeveloper/signup-api
    container_name: signup-api
    env_file: ./microservices.env
    environment:
      - PORT=3001
    networks:
      - microservices_network
    depends_on:
      - redis-cache

  login-api:
    build: ./login
    # image: veludeveloper/login-api
    container_name: login-api
    env_file: ./microservices.env
    environment:
      - PORT=3002
    networks:
      - microservices_network

  reverse-proxy:
    build: ./nginx-proxy
    # image: veludeveloper/nginx-proxy
    container_name: api-proxy
    restart: always
    networks:
      - microservices_network
    ports:
      - "80:80"
    depends_on:
      - login-api
      - signup-api
      - create-project-api
  
  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    env_file: ./microservices.env
    restart: always
    ports:
      - '6379:6379'
    command: /bin/sh -c 'redis-server --save 60 1 --loglevel warning --requirepass $$REDIS_PASSWORD'
    volumes: 
      - cache:/data
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  cache:
    driver: local