services:
  create-project-api:
    # build: ./create-project
    image: veludeveloper/create-project-api
    container_name: create-project-api
    env_file: ./microservices.env
    environment:
      - PORT=3000
    networks:
      - microservices_network

  signup-api:
    # build: ./signup
    image: veludeveloper/signup-api
    container_name: signup-api
    env_file: ./microservices.env
    environment:
      - PORT=3001
    networks:
      - microservices_network
    depends_on:
      - redis-cache

  login-api:
    # build: ./login
    image: veludeveloper/login-api
    container_name: login-api
    env_file: ./microservices.env
    environment:
      - PORT=3002
    networks:
      - microservices_network

  create-task-api:
    # build: ./create-task
    image: veludeveloper/create-task-api
    container_name: create-task-api
    env_file: ./microservices.env
    environment:
      - PORT=3003
    networks:
      - microservices_network

  delete-task-api:
    # build: ./delete-task
    image: veludeveloper/delete-task-api
    container_name: delete-task-api
    env_file: ./microservices.env
    environment:
      - PORT=3004
    networks:
      - microservices_network

  get-tasks-api:
    # build: ./get-tasks
    image: veludeveloper/get-tasks-api
    container_name: get-tasks-api
    env_file: ./microservices.env
    environment:
      - PORT=3008
    networks:
      - microservices_network

  get-projects-api:
    # build: ./get-projects
    image: veludeveloper/get-projects-api
    container_name: get-projects-api
    env_file: ./microservices.env
    environment:
      - PORT=3009
    networks:
      - microservices_network

  get-project-by-id-api:
    # build: ./get-project-by-id
    image: veludeveloper/get-project-by-id-api
    container_name: get-project-by-id-api
    env_file: ./microservices.env
    environment:
      - PORT=3010
    networks:
      - microservices_network

  reverse-proxy:
    # build: ./nginx-proxy
    image: veludeveloper/nginx-proxy
    container_name: api-proxy
    restart: always
    networks:
      - microservices_network
    ports:
      - "80:80"
    depends_on:
      - login-api
      - signup-api
      - create-project-api
  
  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    env_file: ./microservices.env
    restart: always
    ports:
      - '6379:6379'
    command: /bin/sh -c 'redis-server --save 60 1 --loglevel warning --requirepass $$REDIS_PASSWORD'
    volumes: 
      - cache:/data
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  cache:
    driver: local