name: CreateProjectAPI

on:
  push:
    branches:
      - main
    paths:
      - 'create-project/**'
      - '.github/workflows/create-project.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: NodeJS Install, Unit Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './create-project/package-lock.json'

    - name: Install Dependencies
      run: npm install
      working-directory: ./create-project

    - name: Unit Test & Coverage
      run: npm run test --if-present
      working-directory: ./create-project

  docker:
    needs: build
    name: Docker Build and Push
    # Docker build stage will run only for 'push' event
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./create-project
          file: ./create-project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/create-project-api:latest
