name: UpdateTaskAPI

on:
  push:
    branches:
      - main
    paths:
      - 'update-task/**'
      - '.github/workflows/update-task.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: NodeJS Install, Unit Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './update-task/package-lock.json'

    - name: Install Dependencies
      run: npm install
      working-directory: ./update-task

    - name: Unit Test & Coverage
      run: npm run test --if-present
      working-directory: ./update-task

  docker:
    needs: build
    name: Docker Build and Push
    # Docker build stage will run only for 'push' event
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./update-task
          file: ./update-task/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/update-task-api:latest
